version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  foodgram:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./gateway/
    restart: always
    env_file: .env
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/media/
